---
title: "MVG Bikes 2021 - Bike Ride Analysis"
author: "Antoine Thomas"
date: "`r Sys.Date()`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggmap)
library(geosphere)
library(furrr)
library(parallel)
library(lubridate)
library(padr)
library(RColorBrewer)
library(factoextra)
```

# Loading in Data
```{r loading data, message=FALSE, warning=FALSE}
# Reading in raw data and formatting variable
df_rides_2021 <- read_csv2("MVG_Rad_Fahrten_2021.csv") %>%
  mutate(STARTLAT = as.character(STARTLAT),
         ENDLAT = as.character(ENDLAT),
         STARTLON = as.character(STARTLON),
         ENDLON = as.character(ENDLON)) %>%
  mutate(STARTLAT = gsub("(.{2})(.*)", "\\1.\\2", STARTLAT),
         ENDLAT = gsub("(.{2})(.*)", "\\1.\\2", ENDLAT),
         STARTLON = gsub("(.{2})(.*)", "\\1.\\2", STARTLON),
         ENDLON = gsub("(.{2})(.*)", "\\1.\\2", ENDLON)) %>%
   mutate(STARTLAT = as.numeric(STARTLAT),
         ENDLAT = as.numeric(ENDLAT),
         STARTLON = as.numeric(STARTLON),
         ENDLON = as.numeric(ENDLON)) %>%
  rename(start_time = STARTTIME,
         end_time = ENDTIME,
         start_lat = STARTLAT,
         start_lon = STARTLON,
         end_lat = ENDLAT,
         end_lon = ENDLON,
         rental_is_station = RENTAL_IS_STATION,
         rental_station_name = RENTAL_STATION_NAME,
         return_is_station = RETURN_IS_STATION,
         return_station_name = RETURN_STATION_NAME)

```

# Bike Stations in Munich
```{r Bike Stations, message=FALSE, warning=FALSE}

# Filtering for all stations where rides started
start_stations <- df_rides_2021 %>%
  filter(!is.na(rental_station_name)) %>%
  select(start_lat, start_lon, rental_station_name) %>%
  distinct() %>%
  rename(
    lat = start_lat,
    lon = start_lon,
    station_name = rental_station_name
    )

# Filtering for all stations where rides ended
end_stations <- df_rides_2021 %>%
  filter(!is.na(return_station_name)) %>%
  select(end_lat, end_lon, return_station_name) %>%
  distinct() %>%
  rename(
    lat = end_lat,
    lon = end_lon,
    station_name = return_station_name
    )

# Merging all stations
all_stations <- end_stations %>%
  anti_join(start_stations, by = "station_name") %>%
  bind_rows(start_stations)


# Remove unnecessary data frames
rm(start_stations, end_stations)

# Creating bbox to plos
munich_bbox <- make_bbox(lon = all_stations$lon,
                         lat = all_stations$lat,
                         f = c(.26,.05))

# Loading map from osm
munich <- get_stamenmap(bbox = munich_bbox, zoom = 12, maptype = "terrain")

# Creating a plot with all MVG bike stations
ggmap(munich) +
  geom_point(aes(x = lon, y = lat), 
             data = all_stations, 
             color='black', 
             fill='#4562A2', 
             shape=21) +
  theme_bw() +
  theme(plot.title = element_text(face = "bold")) +
  labs(x = "Longitude",
       y = "Latitude",
       title = "MVG Bike Stations 2021",
       caption = "Map Data: OpenStreetMap")

# Removing unnecessary data structures
rm(munich)

```

# Data Cleaning
```{r Data Cleaning, message=FALSE, warning=FALSE}

munich_bbox_filter <- make_bbox(
  lon = all_stations$lon,
  lat = all_stations$lat,
  f = c(.1, .1)
)

compute_dist <- function(slon, slat, elon, elat) {
  m_start_end <- matrix(
    c(
      slon, elon,
      slat, elat
    ),
    nrow = 2
  )
  colnames(m_start_end) <- c("longitude", "latitude")
  rownames(m_start_end) <- c("point_1", "point_2")
  distHaversine(m_start_end) / 1000
}

plan(multisession, workers = detectCores() - 1)
df_rides_2021_cl <- df_rides_2021 %>%
  # Filtering rides out of bbox range
  mutate(duration = as.numeric(end_time - start_time) / 60) %>%
  # Filtering out rides shorter than 5 mins and rides longer than 5 hours
  filter(duration > 3 & duration < 300) %>%
  # Filtering out rides that are out of the bbox range
  filter(
    start_lon > munich_bbox["left"] & start_lon < munich_bbox["right"],
    end_lon > munich_bbox["left"] & end_lon < munich_bbox["right"],
    start_lat > munich_bbox["bottom"] & start_lat < munich_bbox["top"],
    end_lat > munich_bbox["bottom"] & end_lat < munich_bbox["top"]
  ) %>%
  # Computing distances between start and end location
  mutate(distance = as.numeric(future_pmap(.l = list(start_lon, start_lat, end_lon, end_lat), .f = compute_dist))) %>%
  # Filtering out rides with a higher distance than 300m (except 0m)
  filter(distance == 0 | distance > 0.3) %>%
  # Filtering out rides with a distance of 0m and a duration of less than 30 min
  filter(!(distance == 0 & duration < 30)) %>%
  mutate(
    weekday = wday(start_time, label = T),
    month = month(start_time, label = T)
  )

rm(munich_bbox_filter)


```

# Simple Analysis
```{r simple analytics, message=FALSE, warning=FALSE}
# Amount of rides on specific weekdays for each month
getSeason <- function(month) {
    if (month %in% c("Dec","Jan","Feb")) {
      return("Winter")
    } else if (month %in% c("Mar", "Apr", "May")) {
      return("Spring")
    } else if (month %in% c("Jun", "Jul", "Aug")) {
      return("Summer")
    } else {
      return("Fall")
    }
}

color_palette <- colorRampPalette(brewer.pal(8, "Set1"))(12)
df_rides_2021_cl %>%
  group_by(weekday, month) %>%
  summarise(n_rides = n()) %>%
  ungroup() %>%
  mutate(
    month = as.factor(month),
    season = unlist(map(.x = month, .f = getSeason)),
    season = factor(season, levels = c("Spring", "Summer", "Fall", "Winter")),
    weekday = factor(weekday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
  ) %>%
  ggplot(aes(x = weekday, y = n_rides, colour = month)) +
  geom_line(aes(group = month)) +
  geom_point() +
  facet_wrap(~season) +
  scale_colour_manual(values = color_palette) +
  labs(
    y = "Amount of rides",
    x = "Day of the week",
    colour = "",
    title = "Amount of bike rides on specific days of the week"
  ) +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))


# Average ride duration on specific weekdays for each month
df_rides_2021_cl %>%
  group_by(weekday, month) %>%
  summarise(avg_ride_time = mean(duration)) %>%
  ungroup() %>%
  mutate(
    month = as.factor(month),
    season = unlist(map(.x = month, .f = getSeason)),
    season = factor(season, levels = c("Spring", "Summer", "Fall", "Winter")),
    weekday = factor(weekday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
  ) %>%
  ggplot(aes(x = weekday, y = avg_ride_time, colour = month)) +
  geom_line(aes(group = month)) +
  geom_point() +
  facet_wrap(~season) +
  scale_colour_manual(values = color_palette) +
  labs(
    y = "Average ride duration (min)",
    x = "Day of the week",
    colour = "",
    title = "Average bike ride duration on specific days of the week"
  ) +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))
```

# Clustering of Usage Areas
```{r Usage Area Clustering, message=FALSE, warning=FALSE}

getRides_month_wday <- function(wday, mth) {
  df_rides_2021_cl %>%
    filter(
      weekday == wday,
      month == mth
    )
}

splitted_rides <- expand.grid(
  weekday = unique(df_rides_2021_cl$weekday),
  month = unique(df_rides_2021_cl$month)
) %>%
  mutate(rides = map2(.x = weekday, .y = month, .f = getRides_month_wday))

set.seed(21)
df_rides_2021_cl$cluster <- df_rides_2021_cl %>%
  select(start_lat, start_lon) %>%
  kmeans(centers = 15) %>%
  .$cluster

df_rides_2021_cl <- df_rides_2021_cl %>%
  mutate(cluster = as.factor(cluster))

hull <- df_rides_2021_cl %>%
  group_by(cluster) %>%
  slice(chull(start_lon, start_lat))

munich <- get_stamenmap(bbox = munich_bbox, zoom = 12, maptype = "terrain")

color_palette <- colorRampPalette(brewer.pal(8, "Set1"))(15)
ggmap(munich) +
  geom_polygon(aes(x = start_lon, y = start_lat, colour = cluster, fill = cluster), 
             data = hull, alpha = 0.5) +
  scale_colour_manual(values = color_palette) +
  scale_fill_manual(values = color_palette) +
  theme_bw() +
  theme(plot.title = element_text(face = "bold")) +
  labs(x = "Longitude",
       y = "Latitude",
       fill = "Area",
       colour = "Area",
       title = "Areas of started MVG Bike rides",
       caption = "Map Data: OpenStreetMap")

```